name: Auto-Publish Music Clips

on:
  push:
    paths:
      - 'songs/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python and FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          pip3 install --upgrade pip
          python3 -m pip install openai-whisper moviepy==1.0.3 google-api-python-client google-auth-httplib2 google-auth-oauthlib pyyaml

      - name: Run publish script
        env:
          YOUTUBE_CLIENT_SECRETS: ${{ secrets.YOUTUBE_CLIENT_SECRETS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 scripts/publish_clips.py
