name: Render Music Clips

on:
  push:
    paths:
      - 'songs/**'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python, FFmpeg, and ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick python3-pip
          pip3 install --upgrade pip
          pip3 install openai-whisper moviepy==1.0.3

      - name: Run publish script
        run: python3 scripts/publish_clips.py

      - name: Upload video artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rendered-clips
          path: output/*.mp4
