name: Render Music Clips

on:
  push:
    paths:
      - 'songs/**'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python, FFmpeg, and ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip imagemagick
          pip3 install --upgrade pip
          pip3 install openai-whisper moviepy==1.0.3

          # Fix ImageMagick Security Policy
          sudo bash -c 'cat > /etc/ImageMagick-6/policy.xml' << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE policymap [
            <!ELEMENT policymap (policy)*>
            <!ATTLIST policymap xmlns CDATA #FIXED ''>
            <!ELEMENT policy EMPTY>
            <!ATTLIST policy domain NMTOKEN #REQUIRED
                             name NMTOKEN #IMPLIED
                             pattern CDATA #IMPLIED
                             rights NMTOKEN #IMPLIED
                             stealth NMTOKEN #IMPLIED
                             value CDATA #IMPLIED>
          ]>
          <policymap>
            <policy domain="coder" rights="read|write" pattern="PNG" />
            <policy domain="coder" rights="read|write" pattern="TEXT" />
            <policy domain="coder" rights="read|write" pattern="LABEL" />
            <policy domain="coder" rights="read|write" pattern="PDF" />
            <policy domain="resource" name="memory" value="2GiB"/>
            <policy domain="resource" name="map" value="4GiB"/>
            <policy domain="resource" name="area" value="1GB"/>
            <policy domain="resource" name="disk" value="16GB"/>
          </policymap>
          EOF

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cache-v1
          restore-keys: |
            ${{ runner.os }}-pip-cache-

      - name: Cache Whisper models
        uses: actions/cache@v4
        with:
          path: ~/.cache/whisper
          key: ${{ runner.os }}-whisper-base-v1
          restore-keys: |
            ${{ runner.os }}-whisper-base-

      - name: Run publish script
        run: python3 scripts/publish_clips.py

      - name: Upload video artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rendered-clips
          path: output/*.mp4
