name: Render Music Clips (Alternative)

on:
  push:
    paths:
      - 'songs/**'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          ffmpeg -version  # FFmpeg kurulumunu doğrula

      - name: Run publish script
        run: python scripts/publish_clips_alt.py
        env:
          PYTHONUNBUFFERED: 1

      - name: Upload video artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rendered-clips
          path: output/*.mp4