name: Render Music Clips

on:
  push:
    paths:
      - 'songs/**'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python, FFmpeg, and ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip imagemagick
          pip3 install --upgrade pip
          pip3 install openai-whisper moviepy==1.0.3

          # Fix ImageMagick Security Policy
          sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/^.*policy.*coder.*none.*TEXT.*//' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/^.*policy.*coder.*none.*LABEL.*//' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/^.*policy.*coder.*none.*PNG.*//' /etc/ImageMagick-6/policy.xml

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cache-v1
          restore-keys: |
            ${{ runner.os }}-pip-cache-

      - name: Cache Whisper models
        uses: actions/cache@v4
        with:
          path: ~/.cache/whisper
          key: ${{ runner.os }}-whisper-base-v1
          restore-keys: |
            ${{ runner.os }}-whisper-base-

      - name: Run publish script
        run: python3 scripts/publish_clips.py

      - name: Upload video artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rendered-clips
          path: output/*.mp4
